algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2026
// Seção de Declarações 
var
n1, n2,adicao:inteiro
inicio
escreva("digite um número inteiro: ")
leia(n1)
escreva("agora digite outro para a soma: ")
leia(n2)
adicao<-n1+n2
se(adicao>30) entao
escreval("soma maior que 30")
senao
se(adicao=30) entao
escreval("soma igual a 30")
senao
escreval("soma menor que 30")
fimse
fimse
escreva("resultado da soma =", adicao)
fimalgoritmo
