algoritmo "semnome"
// Função :
// Autor :
// Data : 18/03/2026
// Seção de Declarações 
var
nomprod:caracter
preunit,quantcompra,total:real
inicio
escreva(" digite o nome do produto: ")
leia(nomprod)
escreva("quantas unidades do produto foi comprada? ")
leia(quantcompra)
escreva("digite o preço unitário do produto: ")
leia (preunit)
total<-preunit*quantcompra
escreva("o preço total é ",total,"; a quantidade comprada foi de ",quantcompra, "; e o preço unitário é ",preunit)
fimalgoritmo
