algoritmo "oliokinho meo"
// Função :
// Autor :
// Data : 04/03/2026
// Seção de Declarações 
var
numero1, numero2,dobro1, triplo2, resultado_soma: inteiro
inicio
escreva("digite o numero1 ")
leia (numero1)
escreva("agora digite o numero2 ")
leia (numero2)
resultado_soma<-numero1+numero2
dobro1<-numero1*2
triplo2<-numero2*3
escreva ("o resultado da soma é ", resultado_soma, ",o dobro do primeiro é ",dobro1, " e o triplo do segundo é ", triplo2)
fimalgoritmo
