algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2026
// Seção de Declarações 
var
n1, n2:caracter
p1, p2 :real
inicio
escreva("digite o nome da primeira pessoa: ")
leia(n1)
escreva("e o peso em quilos: ")
leia(p1)
escreva("digite o nome da segunda pessoa: ")
leia (n2)
escreva("e o peso da segunda pessoa: ")
leia (p2)
se(p1>p2)entao
escreva("o cliente ",n1," é o mais pesado")
senao
se (p1=p2)entao
escreva("ambos os clientes ",n1, " e ",n2," têm o mesmo peso")
senao
escreva("o usuário ",n2, " é o mais pesado")
fimse
fimse
fimalgoritmo
