algoritmo "semnome"
// Função :
// Autor :
// Data : 01/04/2026
// Seção de Declarações 
var
n1,n2:caracter
alt1,alt2:real
inicio
escreva("digite o nome da primeira pessoa ")
leia(n1)
escreva("e sua altura ")
leia(alt1)
escreva("agr o nome da segunda pessoa ")
leia(n2)
escreva("e sua altura ")
leia(alt2)
se (alt1>alt2) entao
escreva(n1," é a pessoa mais alta com ",alt1," metros")
senao
escreva(n2," é a pessoa mais alta com ",alt2," metros")
fimse
fimalgoritmo
