algoritmo "semnome"
// Função :
// Autor :
// Data : 01/04/2026
// Seção de Declarações 
var
n1,n2:caracter
id1,id2:inteiro
inicio
escreva("informe o nome da primeira pessoa ")
leia(n1)
escreva("e sua idade ")
leia(id1)
escreva("agr digite o nome da segunda pessoa ")
leia(n2)
escreva("e a idade ")
leia(id2)
se (id1>id2) entao
escreva("a pessoa mais velha é ",n1)
senao
escreva("a pessoa mais velha é ",n2)
fimse
fimalgoritmo
