algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2026
// Seção de Declarações 
var
ladoa,ladob,area,perimetro:real
inicio
escreva("digite a medida do lado maior do retangulo, em metros: ")
leia(ladoa)
escreva("agora a medida do lado menor, também em metros: ")
leia (ladob)
perimetro<-2*ladoa+2*ladob
area<- ladoa*ladob
escreva("o perimetro equivale á ",perimetro, " e a área equivale á ",area)
fimalgoritmo
